config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: "registrations"
  }
  
  resources :users
  resources :places
  resources :categories
  resources :cities do
    member do
      get :place
    end
  end
  resources :houses do
    member do
      get :image
    end
    resources :photos
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get 'myregistration_choose' => 'myregistration#choose'
  get 'myregistration_own' => 'myregistration#own'
  get 'myregistration_visitor' => 'myregistration#visitor'
  get 'city_place' => 'places#city'
end

app/models/city.rb
class City < ApplicationRecord
	belongs_to :category
	has_many :houses
	has_many :places

	mount_uploader :cover, CityCoverUploader
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)
    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def place
    @cities = City.all
    @city = City.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :text, :category_id, :cover)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label 'Город' %><br />
  <%= form.text_field :name %>

  <%= form.file_field :cover, :required => true  %>

  <div class="card-content">
    <div class="card-title">
      Ваша категория
    </div>
    <div class="field">
      <%= form.select :category_id, 'Категория': Category.all.collect {|p| [ p.name, p.id] } %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/place.html.erb
<div class="row">
	<div class="col m12 s12">
		<h1><%= @city.name %></h1>
		<div class="citypage-nav">
			<li><%= link_to 'Жилье', city_path(@city) %></li>
			<li><%= link_to 'Куда пойти?', place_city_path(@city) %></li>	
		</div>
	</div>
</div>
<div class="row">
	<% @city.places.each do |place| %>
		<div class="col s12 m4">
			<div class="citypage-house-image">
						
			</div>
			<div class="citypage-house-name">
				<%= link_to place.name, place_path(place) %>	
			</div>
		</div>
	<% end %>
</div>

app/views/cities/show.html.erb
<div class="row">
	<div class="col m12 s12">
		<h1><%= @city.name %></h1>
		<div class="citypage-nav">
			<li><%= link_to 'Жилье', city_path(@city) %></li>
			<li><%= link_to 'Куда пойти?', place_city_path(@city) %></li>	
		</div>

		<%= image_tag @city.cover %>
		
		<div class="row">
			<div class="col m12 s12">
				<p class="bold">Где жить?</p>	
			</div>
			<% @city.houses.each do |house| %>
				<div class="col s12 m4">
					<div class="citypage-house-image">
						<%= image_tag house.cover_photo.try(:img).try(:url) unless house.cover_photo.blank? %>
					</div>
					<div class="citypage-house-name">
						<%= link_to house.name, house_path(house) %>	
					</div>
				</div>
			<% end %>
		</div>
		<div class="row">
			<div class="col m12 s12">
				<p class="bold">Куда пойти?</p>	
			</div>
			<% @city.places.each do |place| %>
				<div class="col s12 m4">
					<div class="citypage-house-image">
							
					</div>
					<div class="citypage-house-name">
						<%= link_to place.name, place_path(place) %>	
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>