config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: "registrations"
  }
  
  resources :users
  resources :places
  resources :categories
  resources :cities do
    member do
      get :place
    end
  end
  resources :houses do
    member do
      get :image
    end
    resources :photos
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get 'myregistration_choose' => 'myregistration#choose'
  get 'myregistration_own' => 'myregistration#own'
  get 'myregistration_visitor' => 'myregistration#visitor'
  get 'city_place' => 'places#city'
end

app/models/place.rb
class Place < ApplicationRecord
	belongs_to :city

	geocoded_by :address
	def address
	  [cityname, street].compact.join(', ')
	end
	after_validation :geocode  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @key = Rails.application.secrets.google_places_key
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :category_id, :city_id, :type_id, :address, :latitude, :longitude, :street, :cityname, :time_work, :site, :phone)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
	def google_map
		@key = Rails.application.secrets.google_places_key
	  "https://maps.googleapis.com/maps/api/js?key=#{@key}&callback=initMap"
	end

	def google_map_address(id)
		@place = Place.find(params[:id])
		latitude = @place.latitude
		longitude = @place.longitude
	  'function initMap() {
      var myLatLng = {lat: latitude, lng: longitude};

      var map = new google.maps.Map(document.getElementById("map"), {
        center: myLatLng,
        zoom: 4
      });

      var marker = new google.maps.Marker({
        map: map,
        position: myLatLng
      });
    }'
	end
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card-content">
    <div class="card-title">
      Название
    </div>
    <div class="field">
      <%= form.text_field :name %>
    </div>
  </div>

  <div class="card-content">
    <div class="card-title">
      Описание
    </div>
    <div class="field">
      <%= form.text_field :description %>
    </div>
  </div>

  <div class="card-content">
    <div class="card-title">
      Город
    </div>
    <div class="field">
      <%= form.select :city_id, 'Город': City.all.collect {|p| [ p.name, p.id] } %>
    </div>
  </div>

  <div class="card-content">
    <div class="card-title">
      Адрес
    </div>
    <div class="field">
      <%= form.text_field :street %>
    </div>
  </div>

  <div class="card-content">
    <div class="card-title">
      Телефон
    </div>
    <div class="field">
      <%= form.text_field :phone %>
    </div>
  </div>

  <div class="card-content">
    <div class="card-title">
      Время работы
    </div>
    <div class="field">
      <%= form.text_field :time_work %>
    </div>
  </div>

  <div class="card-content">
    <div class="card-title">
      Сайт
    </div>
    <div class="field">
      <%= form.text_field :site %>
    </div>
  </div>

  <%= form.hidden_field :cityname, value: @place.city.name %>

  <div class="actions">
    <%= form.submit 'Отправить', class: 'btn' %>
  </div>
<% end %>

app/views/places/city_place.html.erb
Места

app/views/places/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 m12">
			<h1>Editing Place</h1>

			<%= render 'form', place: @place %>

			<%= link_to 'Show', @place %> |
			<%= link_to 'Back', places_path %>
		</div>
	</div>
</div>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<div class="container">
	<div class="row">
		<div class="col m12 s12">
			<h1><%= @place.name %></h1>
			<p><%= @place.city.name %>, <%= @place.street %></p>
			<hr>
			<p class="bold">Описание</p>
			<p><%= @place.description %></p>
			<hr>
			<p class="bold">Контакты</p>
			<p>Телефон: <%= @place.phone %></p>
			<p>Сайт: <%= link_to @place.site, @place.site %></p>
			<hr>
			<p class="bold">Расположение на карте</p>
			<div id="map" style="width: 100%; height: 600px;"></div>
			<p class="bold">Что есть поблизости</p>

			<%= link_to 'Edit', edit_place_path(@place) %> |
			<%= link_to 'Back', places_path %>

			<script>
				function initMap() {
			      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

			      var map = new google.maps.Map(document.getElementById("map"), {
			        center: myLatLng,
			        zoom: 13
			      });

			      var marker = new google.maps.Marker({
			        map: map,
			        position: myLatLng
			      });
			    }
			</script>

			<%= javascript_include_tag google_map, defer: 'defer', :async => true %>

		</div>
	</div>
</div>